GET https://localhost:5001/WeatherForecast

###
GET https://localhost:5001/

###

GET https://app-appinsightsspike.azurewebsites.net/WeatherForecast
content-type: application/json

###

GET https://app-appinsightsspike.azurewebsites.net/
content-type: application/json

###

GET https://app-appbinsightsspike.azurewebsites.net/
content-type: application/json

###

GET https://app-appbinsightsspike.azurewebsites.net/WeatherForecast
content-type: application/json
